export { default as Login} from './login/Login'
export { default as Signup} from './signup/Signup'
export { default as Home} from './home/Home'
export { default as Hotel} from './hotel/Hotel'
export { default as Rooms} from './rooms/Rooms'
export { default as Room} from './room/Room'